
DROP TABLE if exists ##orders;

SELECT	S.BUSINESSSTRUCTURE_ID,
			S.PRODUCT_ID,
			0 as BUDGET_CAD_AMT,
			S.SALES_CAD_AMT,
			0 as BUDGET_ORDERED_QTY,
			S.SALES_ORDERED_QTY,
			S.CANCELLED_IND,
			S.ORDER_DATE_ID,
			S.CANCEL_DATE_ID,
			S.DOCUMENT_ID,
			S.SOLDTO_CUSTOMER_ID,
			S.SHIPTO_GEOGRAPHY_ID,
			S.INTERCOMPANY_IND,
			0 as TRANSACTION_TYPE_ID
into ##orders
    FROM dbo.F_SALESORDERS S
	INNER JOIN dbo.D_BUSINESSSTRUCTURE BS on S.BUSINESSSTRUCTURE_ID = BS.BUSINESSSTRUCTURE_ID
	INNER JOIN dbo.D_PRODUCTS P on s.PRODUCT_ID = P.PRODUCT_ID -- RAVM 20200901
	--WHERE	S.INTERCOMPANY_IND = 0 	and	BS.COST_CENTER_CODE Not In ('J01121','J01122','J01123') /*ravm 2020901 */ --and (P.FAMILY2_CODE <> 'E01' and P.TYPE1_CODE <> 'E03')
	WHERE	S.INTERCOMPANY_IND = 0 	and	(BS.COST_CENTER_CODE Not like ('J%') OR BS.[BUSINESS_CENTER_CODE] = 'E33')
			and S.PRODUCT_ID Not in (Select distinct P. PRODUCT_ID from dbo.D_PRODUCTS P where P.FAMILY2_CODE = 'E01' and P.TYPE1_CODE = 'E03') -- ravm 20200901
	UNION ALL
	SELECT	B.BUSINESSSTRUCTURE_ID,
			B.PRODUCT_ID,
			B.BUDGET_CAD_AMT,
			0 as SALES_CAD_AMT,
			B.BUDGET_QTY as BUDGET_ORDERED_QTY,
			0 as SALES_ORDERED_QTY,
			0 as CANCELLED_IND,
			B.DATE_ID,
			-1 as CANCEL_DATE_ID,
			0 as DOCUMENT_ID,
			0 as SOLDTO_CUSTOMER_ID,
			B.GEOGRAPHY_ID as SHIPTO_GEOGRAPHY_ID,
			0 as INTERCOMPANY_IND,
			1 as TRANSACTION_TYPE_ID
	FROM dbo.F_BUDGETS B
	INNER JOIN dbo.D_BUSINESSSTRUCTURE BS on B.BUSINESSSTRUCTURE_ID = BS.BUSINESSSTRUCTURE_ID
	--WHERE BS.COST_CENTER_CODE Not In ('J01121','J01122','J01123')
	WHERE	(BS.COST_CENTER_CODE Not like ('J%') OR BS.[BUSINESS_CENTER_CODE] = 'E33') -- ravm 20200901
			and B.PRODUCT_ID Not in (Select distinct P. PRODUCT_ID from dbo.D_PRODUCTS P where P.FAMILY2_CODE = 'E01' and P.TYPE1_CODE = 'E03')
	UNION ALL 
	SELECT	S.BUSINESSSTRUCTURE_ID,
			S.PRODUCT_ID,
			0 as BUDGET_CAD_AMT,
			0 as SALES_CAD_AMT,
			0 as BUDGET_ORDERED_QTY,
			S.SALES_ORDERED_QTY,
			S.CANCELLED_IND,
			S.ORDER_DATE_ID,
			S.CANCEL_DATE_ID,
			S.DOCUMENT_ID,
			S.SOLDTO_CUSTOMER_ID,
			S.SHIPTO_GEOGRAPHY_ID,
			S.INTERCOMPANY_IND,
			2 as TRANSACTION_TYPE_ID
	FROM dbo.F_SALESORDERS S
	INNER JOIN dbo.D_BUSINESSSTRUCTURE BS on S.BUSINESSSTRUCTURE_ID = BS.BUSINESSSTRUCTURE_ID
	INNER JOIN dbo.D_PRODUCTS P on s.PRODUCT_ID = P.PRODUCT_ID
	--WHERE	S.INTERCOMPANY_IND = 0 	and	BS.COST_CENTER_CODE Not In ('J01121','J01122','J01123')  AND P.TYPE1_CODE IN ('E03','E04')
	WHERE	S.INTERCOMPANY_IND = 0 	and	(BS.COST_CENTER_CODE Not like ('J%') OR BS.[BUSINESS_CENTER_CODE] = 'E33')
	AND P.TYPE1_CODE IN ('E03','E04') -- ravm 20200901
	UNION ALL
	-- RAVM 2020-06-12 ADD section to distinct DIUV IN ECOFLO --
	SELECT	B.BUSINESSSTRUCTURE_ID,
			B.PRODUCT_ID,
			B.BUDGET_CAD_AMT,
			0 as SALES_CAD_AMT,
			B.BUDGET_QTY as BUDGET_ORDERED_QTY,
			0 as SALES_ORDERED_QTY,
			0 as CANCELLED_IND,
			B.DATE_ID,
			-1 as CANCEL_DATE_ID,
			0 as DOCUMENT_ID,
			0 as SOLDTO_CUSTOMER_ID,
			B.GEOGRAPHY_ID as SHIPTO_GEOGRAPHY_ID,
			0 as INTERCOMPANY_IND,
			3 as TRANSACTION_TYPE_ID
	FROM dbo.F_BUDGETS B
	INNER JOIN dbo.D_BUSINESSSTRUCTURE BS on B.BUSINESSSTRUCTURE_ID = BS.BUSINESSSTRUCTURE_ID
	INNER JOIN dbo.D_PRODUCTS P on B.PRODUCT_ID = P.PRODUCT_ID
	--WHERE	BS.COST_CENTER_CODE Not In ('J01121','J01122','J01123') AND P.TYPE1_CODE IN ('E03','E04')
	WHERE	(BS.COST_CENTER_CODE Not like ('J%') OR BS.[BUSINESS_CENTER_CODE] = 'E33')
	AND P.TYPE1_CODE IN ('E03','E04') -- ravm 20200901; 
	-- END RAVM 2020-06-12 --
	-- 700130 2022-02-01 ADD section to distinct ND IN ECOFLO --
	UNION ALL 
	SELECT	S.BUSINESSSTRUCTURE_ID,
			S.PRODUCT_ID,
			0 as BUDGET_CAD_AMT,
			0 as SALES_CAD_AMT,
			0 as BUDGET_ORDERED_QTY,
			S.SALES_ORDERED_QTY,
			S.CANCELLED_IND,
			S.ORDER_DATE_ID,
			S.CANCEL_DATE_ID,
			S.DOCUMENT_ID,
			S.SOLDTO_CUSTOMER_ID,
			S.SHIPTO_GEOGRAPHY_ID,
			S.INTERCOMPANY_IND,
			4 as TRANSACTION_TYPE_ID
	FROM dbo.F_SALESORDERS S
	INNER JOIN dbo.D_BUSINESSSTRUCTURE BS on S.BUSINESSSTRUCTURE_ID = BS.BUSINESSSTRUCTURE_ID
	INNER JOIN dbo.D_PRODUCTS P on s.PRODUCT_ID = P.PRODUCT_ID
	--WHERE	S.INTERCOMPANY_IND = 0 	and	BS.COST_CENTER_CODE Not In ('J01121','J01122','J01123')  AND P.TYPE1_CODE IN ('E03','E04')
	WHERE	S.INTERCOMPANY_IND = 0 	and	(BS.COST_CENTER_CODE Not like ('J%') OR BS.[BUSINESS_CENTER_CODE] = 'E33')
	AND P.TYPE1_CODE IN ('E05') AND P.FAMILY3_CODE <> 'E04' -- ravm 20200901
	UNION ALL
	-- 700130 2022-02-01 ADD section to distinct ND IN ECOFLO --
	SELECT	B.BUSINESSSTRUCTURE_ID,
			B.PRODUCT_ID,
			B.BUDGET_CAD_AMT,
			0 as SALES_CAD_AMT,
			B.BUDGET_QTY as BUDGET_ORDERED_QTY,
			0 as SALES_ORDERED_QTY,
			0 as CANCELLED_IND,
			B.DATE_ID,
			-1 as CANCEL_DATE_ID,
			0 as DOCUMENT_ID,
			0 as SOLDTO_CUSTOMER_ID,
			B.GEOGRAPHY_ID as SHIPTO_GEOGRAPHY_ID,
			0 as INTERCOMPANY_IND,
			5 as TRANSACTION_TYPE_ID
	FROM dbo.F_BUDGETS B
	INNER JOIN dbo.D_BUSINESSSTRUCTURE BS on B.BUSINESSSTRUCTURE_ID = BS.BUSINESSSTRUCTURE_ID
	INNER JOIN dbo.D_PRODUCTS P on B.PRODUCT_ID = P.PRODUCT_ID
	--WHERE	BS.COST_CENTER_CODE Not In ('J01121','J01122','J01123') AND P.TYPE1_CODE IN ('E03','E04')
	WHERE	(BS.COST_CENTER_CODE Not like ('J%') OR BS.[BUSINESS_CENTER_CODE] = 'E33')
	AND P.TYPE1_CODE IN ('E05') AND P.FAMILY3_CODE <> 'E04' 
    
    